flyway.url=jdbc:postgresql://postgres:5432/quipupay
flyway.user=quipupay
flyway.password=quipupay
flyway.locations=filesystem:/flyway/sql
flyway.defaultSchema=config
flyway.schemas=config,auth,identity,users,devices,banking,ledger,transactions,cards,payments,files,notifications,risk,audit,admin
flyway.createSchemas=true
flyway.cleanDisabled=true

